### ISSUE TITLE
hardcoded path for bbmap

### ISSUE THREAD

**Issue by smangul1** [AnneHoffmann/tRNA-read-mapping#1]
Hi,

you have hardcoded part for bbmap

you may consider using
./conda install -c bioconda bbmap

Thanks,
Serghei

**Comment by smangul1** [comment]
The same for 
conda install trnascan-se

**Comment by smangul1** [comment]
I am also getting an error when running tRNAscan2bed12.pl

Status: Running Infernal analysis
Use of uninitialized value $F[8] in multiplication (*) at /PHShome/sv188/code/tRNA/tRNA-read-mapping//tRNAscan2bed12.pl line 21, <IN> line 1.

**Comment by jfallmann** [comment]
@smangul1 Thanks for reporting this, the hardcoded paths are a remnant of old times, had to bring bbmap and transcan into bioconda first, will look into this. @fabou-uobaf @AnneHoffmann can you check the perl error pls

**Comment by AnneHoffmann** [comment]
Hallo Jörg,

weißt du genau was die von uns wollen? Anders ging es doch nicht, wir
mussten es doch hard codieren?


LG,
Anne

**Comment by jfallmann** [comment]
@smangul1 Could you please provide us with the trnascan output file you use, we can not reproduce this error on our side

**Comment by jfallmann** [comment]
Expect solved, closing
